### ISSUE TITLE
Nested OR statement expecting conditional operator

### ISSUE THREAD

**Issue by Jademalo** [huderlem/poryscript#40]
I'm trying to check the result of an encounter, to give different outcomes depending on the result.

I assumed that the following would be possible, nesting the two possible outcomes in brackets and ORing between them;
```
if(var(VAR_RESULT) == (B_OUTCOME_RAN || B_OUTCOME_PLAYER_TELEPORTED))
```
However, this throws the following error;
```
PORYSCRIPT ERROR: line 347: left side of binary expression must be var(), flag(), or defeated() operator. Instead, found 'B_OUTCOME_PLAYER_TELEPORTED'
```

In the documentation, it says the following;
```    
# Group nested conditions together with another set of parentheses.
if (flag(FLAG_IS_CHAMPION) && !(flag(FLAG_SYS_TOWER_GOLD) || flag(FLAG_SYS_DOME_GOLD))) {
```

My assumption is that the interpreter doesn't handle OR statements in the way I assumed it would, and that at least one side of the OR needs to be either `flag`, `var`, or `defeated`. However, I'm not sure if this is intended or if it's a bug.

Is this behaviour correct, or is it incorrectly assuming something beside an OR has to be a `flag`, `var`, or `defeated`?

The following works to get the result I want, but feels less elegant than my original assumption.
```
if(var(VAR_RESULT) == B_OUTCOME_RAN || var(VAR_RESULT) == B_OUTCOME_PLAYER_TELEPORTED){
```

**Comment by huderlem** [comment]
You've made a common logical error with your conditionals, unrelated to poryscript.  The following two lines of code have very different meanings.  I'll write them in C to take poryscript out of the equation:

```c
if (var_result == (B_OUTCOME_RAN || B_OUTCOME_PLAYER_TELEPORTED))
if (var_result == B_OUTCOME_RAN || var_result == B_OUTCOME_PLAYER_TELEPORTED)
```

The first line is the same as:
```
if (var_result == 1)
```

while the second line does exactly what you want--check if the player teleported or fled.  So, your "elegant" line of code doesn't do what you want, regardless of poryscript syntax.

As for the poryscript syntax error you're receiving, that's by design.  The only things that can cause a script jump in the pokemon scripting engine are the `flag`, `var`, and `defeated` operations, which set a comparison flag that can be acted upon.  This is why the `||` requires one of those operators on the left side.
